### ISSUE TITLE
::: tip Custom containers don't work

### ISSUE THREAD

**Issue by simonhanmer** [vuepressjs/vuepress-theme-blog#20]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

- [ ] I prepared a reproduction repo, here is the reproduction repo: 

- [x] This issue doesn't need a reproduction repro, here is the steps to reproduce

#### What is expected?
When using the default theme, we can use a markdown extension to provide a container (https://vuepress.vuejs.org/guide/markdown.html#custom-containers).

#### What is actually happening?
Trying to use ::: tip or other container type just renders the text

#### Other relevant information

Package versions:
    "vuepress": "^1.1.0",
    "@vuepress/plugin-blog": "^1.3",
    "@vuepress/theme-blog": "^1.2",

**Comment by ulivz** [comment]
The blog theme doesn't include the container plugin, so you can import it by yourself
