### ISSUE TITLE
Please enable sidebar option

### ISSUE THREAD

**Issue by songololo** [vuepressjs/vuepress-theme-blog#21]
## Feature request

Please enable sidebar navigation, similar to the default vuepress theme.

#### What problem does this feature solve?

It makes navigation simpler and allows structuring the blog by theme.

#### What does the proposed API look like?

The same as the default sidebar configuration for the default vuepress theme.

#### How should this be implemented in your opinion?

Per above.

#### Are you willing to work on this yourself?

If I understand what to do I can try.

**Comment by newsbielt703** [comment]
Hi @songololo.
Since it's not common in a blog theme, you can customize it by [theme-inheritance](https://vuepress.vuejs.org/theme/inheritance.html#theme-inheritance) or simply fork this repo.
