### ISSUE TITLE
Document misspelling

### ISSUE THREAD

**Issue by wangji7** [vuepressjs/vuepress-theme-blog#24]
modifyBlogPluginOptions(blogPlugnOptions) {
      const sitemap = {
        hostname: 'https://yourdomain'
      }

      const comment = {
        service: 'disqus',
        shortname: 'disqus-shortname',
        // service: 'vssue',
        // owner: 'You',
        // repo: 'Your repo',
        // clientId: 'Your clientId',
        // clientSecret: 'Your clientSecret',
      }

      return { ...blogPluginOptions, sitemap, comment }
    },
(blogPlugnOptions)    ...blogPluginOptions   not a parameter

**Comment by newsbielt703** [comment]
Thanks for the report
