### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by unlikenesses** [vuepressjs/vuepress-theme-blog#25]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

- [ ] I prepared a reproduction repo, here is the reproduction repo: 

- [x] This issue doesn't need a reproduction repro, here is the steps to reproduce

1. `yarn create vuepress`
2. `yarn install`
3. Edit a post. Change the `date` of the post to `2019-11-30`.
4. `yarn dev`
5. Go to localhost:8080
6. Instead of seeing "30 November 2019", you see "Invalid date".

#### What is expected?

When a post has a date in the front matter, it should be rendered correctly.

#### What is actually happening?

For some dates, e.g. `2019-11-30`, instead of the date, the string "Invalid date" is shown.

#### Other relevant information

- `npx vuepress info`:

  System:
    OS: Windows 8.1 6.3.9600
    CPU: (4) x64 Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
  Binaries:
    Node: 8.11.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.6.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.0.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: ^1.0.0 => 1.2.0
  npmGlobalPackages:
    vuepress: Not Found

**Comment by newsbielt703** [comment]
Thanks for report.

**Comment by cireu** [comment]
I found that if I use `"YYYY-MM-DD"` instead of `YYYY-MM-DD`, it can be render correctly. I will try to resolve this.

**Comment by cireu** [comment]
@newsbielt703  Please check #27

**Comment by Himself65** [comment]
I think we can use package [moment-js](http://momentjs.cn/), and allow users to modify themself's date formate
