### ISSUE TITLE
Fonts are not in `.vuepress/dist`, making them inaccessible in web context

### ISSUE THREAD

**Issue by Kocal** [vuepressjs/vuepress-theme-blog#40]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

- [ ] I prepared a reproduction repo, here is the reproduction repo: 

- [x] This issue doesn't need a reproduction repro, here is the steps to reproduce:
- open https://example.vuepress-theme-blog.ulivz.com/ or https://ulivz.com/
- open developer tools 
- see error message `Failed to load resource: the server responded with a status of 404 () EJRVQgYoZZY2vCFuvAFWzr-_dSb_.woff2`

#### What is expected?

No errors, the font `EJRVQgYoZZY2vCFuvAFWzr-_dSb_.woff2` and its _variants_ should be here.

#### What is actually happening?

An error happens when trying to load a font.

![Capture d’écran de 2020-01-08 20-48-15](https://user-images.githubusercontent.com/2103975/72010509-44bd7800-3258-11ea-8ed3-addd4586e8dc.png)

Fonts are not shipped in `.vuepress/dist` folder when running `vuepress build`, but I don't understand why because paths used in [`font.styl`](https://github.com/vuepressjs/vuepress-theme-blog/blob/master/styles/font.styl) looks ok, and VP does not output any errors. :confused: 

#### Other relevant information

- `npx vuepress info`: not relevant here

**Comment by newsbielt703** [comment]
I can't reproduce it since I have the font in local, but it definitely can't be access for now.

Thanks for the report.
