### ISSUE TITLE
Section links should not be covered by navbar

### ISSUE THREAD

**Issue by kefranabg** [vuepressjs/vuepress-theme-blog#60]
- [x] I confirm that this is an issue rather than a question.

## Bug report

When clicking on a section link inside of a page, the page scrolls to show that section at the top. However, the navbar covers the header. It would be great to adjust this so the header is not hidden

#### Steps to reproduce

- Go to [this page](https://billyyyyy3320.com/en/2020/01/25/intro-to-vuepress-blog-theme-and-plugin/)
- Clic the "preface" link on the side bar
- Navbar covers the Preface section title

![Capture d’écran 2020-01-26 à 10 53 26](https://user-images.githubusercontent.com/9840435/73133540-4fcf2100-402a-11ea-8c99-9f188975e81f.jpg)

**Comment by newsbielt703** [comment]
Nice catch! I'll fix it ASAP.
