### ISSUE TITLE
Artices can hide in blog list

### ISSUE THREAD

**Issue by Jimzjy** [vuepressjs/vuepress-theme-blog#66]
#### What problem does this feature solve?
Add `secret` support in front matter, so articles can hide in blog list
#### What does the proposed API look like?
```
---
secret: true
---
```
#### How should this be implemented in your opinion?
Add a filter in BaseListLayout `pages`
#### Are you willing to work on this yourself?
Yes

**Comment by newsbielt703** [comment]
Why you want to hide your posts?

**Comment by Jimzjy** [comment]
I dont want to delete some posts, so it will be great if i can hide it, 😁other people may not simply find it.

**Comment by newsbielt703** [comment]
It reminds me of `Drafts` which we'll probably support it. I believe it can somehow meet your need, right?

For now, you can simply move those posts you want to hide from `_posts` to another directory, such as `_secret`.

**Comment by Jimzjy** [comment]
> It reminds me of `Drafts` which we'll probably support it. I believe it can somehow meet your need, right?
> 
> For now, you can simply move those posts you want to hide from `_posts` to another directory, such as `_secret` or `_archived`.

Oh, it's a good way😃
