### ISSUE TITLE
Footer Contact List is Too Limited

### ISSUE THREAD

**Issue by RehanSaeed** [vuepressjs/vuepress-theme-blog#69]
#### What problem does this feature solve?

I want to add YouTube and StackOverflow links in the footer contact list. Here is an excerpt from my `config.js`:

```
footer: {
  contact: [
    {
      type: 'twitter',
      link: 'https://twitter.com/RehanSaeedUK',
    },
    {
      type: 'web',
      link: 'https://www.youtube.com/channel/UC6geox4JkY11093RqecELGA',
    },
    {
      type: 'github',
      link: 'https://github.com/RehanSaeed',
    },
    {
      type: 'web',
      link: 'https://stackoverflow.com/users/1212017/muhammad-rehan-saeed',
    }
  ],
}
```

Unfortunately, there is a very limited set of `type`'s that are allowed. I could use the `web` type but then I get two globe icons and it's not clear what they do.

#### What does the proposed API look like?

Add a way to specify custom SVG images.

#### How should this be implemented in your opinion?

Maybe a link to an SVG file.

**Comment by newsbielt703** [comment]
> Welcome contribution of adding more built-in contact type.
