### ISSUE TITLE
Add vuepress-plugin-container 

### ISSUE THREAD

**Issue by ChungZH** [vuepressjs/vuepress-theme-blog#76]
## Feature request
Add vuepress-plugin-container in `theme-blog`.

#### What problem does this feature solve?

Use container in markdown files.

#### How should this be implemented in your opinion?
Add this plugin.
#### Are you willing to work on this yourself?
No.

**Comment by newsbielt703** [comment]
Duplicate of #20, as it's not a widely-used feature for blogging, you can import it by yourself.
