### ISSUE TITLE
Unable to use built-in component?

### ISSUE THREAD

**Issue by kid1412621** [vuepressjs/vuepress-theme-blog#81]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

- [ ] I prepared a reproduction repo, here is the reproduction repo: 

- [x] This issue doesn't need a reproduction repro, here is the steps to reproduce

#### What is expected?
such as, `<Badge text="beta" type="warning"/>`
#### What is actually happening?
same thing as the default theme
#### Other relevant information

- `npx vuepress info`:
```
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: Not Found
    Safari: 13.1
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: Not Found
  npmGlobalPackages:
    vuepress: 1.3.1
```

**Comment by newsbielt703** [comment]
Check out [the badge in docs](https://vuepress.vuejs.org/guide/using-vue.html#badge), it's only built-in for default theme.

**Comment by kid1412621** [comment]
thx, another question, why `@vuepress/medium-zoom` doesn't work anymore in blog theme?
