### ISSUE TITLE
Cannot click tag labels (on part of the tag without text)

### ISSUE THREAD

**Issue by twitwi** [vuepressjs/vuepress-theme-blog#84]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

In a existing vuepress blog, visit a post that has tags, and click on one of the tag but outside of the text of the tag.

- [ ] I prepared a reproduction repo, here is the reproduction repo: 

- [x] This issue doesn't need a reproduction repro, here is the steps to reproduce

#### What is expected?

It navigates to the tag page (listing all the posts with the clicked tag).

#### What is actually happening?

Nothing happens, the link is not followed.

#### Other relevant information

This UX issue probably comes from the fact that the tag itself is a `li` in which only the text is a `a` (with some `::before` etc).
Having a structure like `li>a>span` and changing most of the css to apply on `a` instead of `li` and on `span` instead of `a` should be close to solving the issue.

**Comment by newsbielt703** [comment]
Thanks for the report!
